[theme]
primaryColor = "#FF4500"
backgroundColor = "#0d0d0d"
secondaryBackgroundColor = "#1a1a1a"
textColor = "#ffffff"
font = "sans serif"

[client]
showErrorDetails = false

[server]
maxUploadSize = 200
enableXsrfProtection = true
headless = true
